version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gymratnote
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gymratnote
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: